### ISSUE TITLE
Overlapping destination and source directory broken

### ISSUE THREAD

**Issue by heikkiorsila** [rdiff-backup/rdiff-backup#296]

**Comment by heikkiorsila** [comment]
I'm testing "ppa:rdiff-backup/rdiff-backup-development" repository to backup a following setup:

/home/foo/tmp: All the files (source directory)
/home/foo/tmp/files: contains files to backup
/home/foo/tmp/backups: contains the backups (destination directory)

Note: the destination directory overlaps with the source directory.

I'm running:  rdiff-backup --exclude /home/foo/tmp/backups /home/foo/tmp /home/foo/tmp/backups

I'm using --exclude /home/foo/tmp/backups to avoid infinite regress.

The error I get is:

$ rdiff-backup --exclude /home/foo/tmp/backups /home/foo/tmp /home/foo/tmp/backups
Exception ''generator' object has no attribute 'Select'' raised of class '<class 'AttributeError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 430, in Backup
    backup_warn_if_infinite_regress(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 588, in backup_warn_if_infinite_regress
    if not Globals.select_mirror.Select(relative_rpout):

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 430, in Backup
    backup_warn_if_infinite_regress(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 588, in backup_warn_if_infinite_regress
    if not Globals.select_mirror.Select(relative_rpout):
AttributeError: 'generator' object has no attribute 'Select'

Globals.select_mirror is a generator of RPaths (from selection.Select.Iterate_fast()), so it does not have Select() method.

This used to work with the old stable version..

**Comment by heikkiorsila** [comment]
The old stable version 1.2.8 in Ubuntu just works without warning:

$ rdiff-backup --exclude /home/foo/tmp/backups /home/foo/tmp /home/foo/tmp/backups
shd@iln:/home/foo/tmp$ 

Note: I get this error with the new version of rdiff-backup even if I remove all the old backup files under /home/foo/tmp/backups/.

**Comment by heikkiorsila** [comment]
If I execute the backup to a non-overlapping destination path, it works just fine with the new version:

$  rdiff-backup --exclude /home/foo/tmp/backups /home/foo/tmp /home/foo/data/backup-elsewhere
$

**Comment by ericzolf** [comment]
I can confirm that there is an issue, quite simple to reproduce:

```
mkdir -p /tmp/backup/{source,target}
rdiff-backup --exclude /tmp/backup/target /tmp/backup /tmp/backup/target
[...]    Backup(rps[0], rps[1])
  File "/home/ericl/.local/lib/python3.7/site-packages/rdiff_backup/Main.py", line 430, in Backup
    backup_warn_if_infinite_regress(rpin, rpout)
  File "/home/ericl/.local/lib/python3.7/site-packages/rdiff_backup/Main.py", line 588, in backup_warn_if_infinite_regress
    if not Globals.select_mirror.Select(relative_rpout):
AttributeError: 'generator' object has no attribute 'Select'
```

And it's definitely a regression as it works with 1.2.8

**Comment by ericzolf** [comment]
Working on it. I have a fix but it breaks something else. The issue is die to some changes in iterators.

**Comment by heikkiorsila** [comment]
Still not working:
```
$ rdiff-backup --version
rdiff-backup 1.9.0b1.dev20+g741a98d.ubuntu19.4.1
$ rdiff-backup --exclude /home/foo/tmp/backups /home/foo/tmp /home/foo/tmp/backups
Exception ''generator' object has no attribute 'Select'' raised of class '<class 'AttributeError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 430, in Backup
    backup_warn_if_infinite_regress(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 588, in backup_warn_if_infinite_regress
    if not Globals.select_mirror.Select(relative_rpout):

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 430, in Backup
    backup_warn_if_infinite_regress(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 588, in backup_warn_if_infinite_regress
    if not Globals.select_mirror.Select(relative_rpout):
AttributeError: 'generator' object has no attribute 'Select'


```

**Comment by ericzolf** [comment]
Use 2.0.0, it has the fix.
