### PR TITLE
Fix implicit declaration of function ‘dup’ under Python 3.13

### LINKED ISSUE #934: [BUG] rdiff-backup fails to build with Python 3.13: Missing <unistd.h> declaration
## Bug summary

rdiff-backup fails to build with Python 3.13.0a1.

## Version, Python, Operating System

rdiff-backup-2.2.6

## rdiff-backup call

Test mass rebuild of all packages with Python 3.13.

## What happened and what did you expect?

rdiff-backup fails to build with Python 3.13.0a1.

```
src/_librsyncmodule.c: In function ‘_librsync_new_patchmaker’:
src/_librsyncmodule.c:407:16: error: implicit declaration of function ‘dup’ [-Werror=implicit-function-declaration]
  407 |   int dup_fd = dup(python_fd);
      |                ^~~
```

## More information

From [Red Hat Bugzilla – Bug 2245885](https://bugzilla.redhat.com/show_bug.cgi?id=2245885)

According to [https://docs.python.org/3.13/whatsnew/3.13.html](https://docs.python.org/3.13/whatsnew/3.13.html):

Python.h no longer includes the <unistd.h> standard header file.
If needed, it should now be included explicitly.
For example, it provides the functions: read(), write(), close(), isatty(), lseek(), getpid(), getcwd(), sysconf() and getpagesize().
As a consequence, _POSIX_SEMAPHORES and _POSIX_THREADS macros are no longer defined by Python.h.
The HAVE_UNISTD_H and HAVE_PTHREAD_H macros defined by Python.h can be used to decide if <unistd.h> and <pthread.h> header files can be included.
(Contributed by Victor Stinner in gh-108765.)

For the build logs, see:
[https://copr-be.cloud.fedoraproject.org/results/@python/python3.13/fedora-rawhide-x86_64/06546852-rdiff-backup/](https://copr-be.cloud.fedoraproject.org/results/@python/python3.13/fedora-rawhide-x86_64/06546852-rdiff-backup/)

For all our attempts to build rdiff-backup with Python 3.13, see:
[https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/rdiff-backup/](https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/rdiff-backup/)

Testing and mass rebuild of packages is happening in copr.
You can follow these instructions to test locally in mock if your package builds with Python 3.13:
[https://copr.fedorainfracloud.org/coprs/g/python/python3.13/](https://copr.fedorainfracloud.org/coprs/g/python/python3.13/)

Let us know here if you have any questions.

Python 3.13 is planned to be included in Fedora 41.
To make that update smoother, we're building Fedora packages with all pre-releases of Python 3.13.
A build failure prevents us from testing all dependent packages (transitive [Build]Requires),
so if this package is required a lot, it's important for us to get it fixed soon.

We'd appreciate help from the people who know this package best,
but if you don't want to work on this now, let us know so we can try to work around it on our side.

### PR DESCRIPTION
**Pull request by ericzolf**
## Self-Checklist

FIX: rdiff-backup can be compiled with 3.13 without error due to missing dup function from unistd.h, closes #934

- [x] changes to the code have been reflected in the documentation
- [x] changes to the code have been covered by new/modified tests
- [x] commit contains a description of changes relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:

### CODE REVIEW

**Comment by ericzolf** [comment]
@frankcrawford can you please check this PR? I've tried 3.11 on Linux and Windows, and it doesn't break. I've also compiled it with python3.13-3.13.0~a1-1.fc38.x86_64.
Interestingly enough, `./setup.py build` in a 3.13 venv fails without the patch (same error as you reported) and succeeds with it, _but_ `pip install .` in the same venv succeeds in all cases, so I'm not sure what's happening.

**Comment by frankcrawford** [comment]
@ericzolf yes, I'll try and get it built in the right environment to see how it goes.

**Comment by frankcrawford** [comment]
I am slightly confused now, as the latest test build against Python 3.13 succeeds without this patch being applied.

I'm waiting for an update from upstream about why the change.

**Comment by ericzolf** [comment]
In a fresh virtualenv created with `python3.13 -m venv /tmp/py313` I can still reproduce the issue with `./setup.py bdist`:

```
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -I/tmp/py313/include -I/usr/include/python3.13 -c src/_librsyncmodule.c -o build/temp.linux-x86_64-cpython-313/src/_librsyncmodule.o
src/_librsyncmodule.c: In function ‘_librsync_new_patchmaker’:
src/_librsyncmodule.c:407:16: warning: implicit declaration of function ‘dup’ [-Wimplicit-function-declaration]
  407 |   int dup_fd = dup(python_fd);
      |                ^~~
```

BUT the process continues as if nothing bad had happened, where I had in mind that it did fail before (but perhaps it was just because I only called `./setup.py build`. Could it be that you just didn't see the error message because there was no error code or so in the build. As already said `pip install .` doesn't spit any error. As I speak, I'm running the tests and nothing bad seems to happen... I'm no C-programmer but from the look of it, the code should fail if the function `dup` didn't exist!? I'm also confused...

**Comment by frankcrawford** [comment]
The Fedora team have got back to me with the following:

_Sorry for the confusion. We have updated Python to a git snapshot and the removal of the header include was reverted:_
[https://github.com/python/cpython/pull/112046](https://github.com/python/cpython/pull/112046)

However, reading that discussion, something related may reappear for Python 3.14, as they are looking at how to clean up the header files.

**Comment by ericzolf** [comment]
OK, I would merge it, it doesn't hurt and we would be already ready for 2.14. Do you see any drawback (beside a very small increase in complexity)?

**Comment by frankcrawford** [comment]
No, I don't see any reason not to, although we should keep an eye on it coming up toe Python 3.14 release, they may make some other changes.
