### ISSUE TITLE
[BUG] src/rdiff-backup-delete doesn't work with python 2.7

### ISSUE THREAD

**Issue by fireartist** [rdiff-backup/rdiff-backup#690]
## Bug summary

The script `rdiff-backup-delete` doesn't work with python 2.7

## Version, Python, Operating System

Lastest git master branch (847c8bd409344e9fd669ea27dd1894efbaab0735)

Running redhat 7

## rdiff-backup call

```
sudo ~/checkout/rdiff-backup/src/rdiff-backup-delete --dry-run path/to/file
```

## What happened and what did you expect?

```
Traceback (most recent call last):
  File "/home/cafranks/checkout/rdiff-backup/src/rdiff-backup-delete", line 454, in <module>
    main()
  File "/home/cafranks/checkout/rdiff-backup/src/rdiff-backup-delete", line 429, in main
    root, relpath, dry_run = _parse_options()
  File "/home/cafranks/checkout/rdiff-backup/src/rdiff-backup-delete", line 183, in _parse_options
    if (b"rdiff-backup-data" in full_path.split(os.fsencode(os.sep))
AttributeError: 'module' object has no attribute 'fsencode'
```

## More information

I can see the code is setting flags for python versions PY2, PY26, PY3.
Given the other scripts (`rdiff-backup` and `rdiff-backup-statistics`) both have `python3` hardcoded in their shbang lines - will you accept a patch to remove all support for python 2 specific code-paths in `rdiff-backup-delete`, and change its shbang to point to `python3` instead of `python`?

**Comment by ericzolf** [comment]
Aha, we discussed about it in https://github.com/rdiff-backup/rdiff-backup/pull/474 but we both didn't see that the changes broke python 2 compatibility. As said,  Patrik's decision...

**Comment by ikus060** [comment]
I've deliver a "working" version for python2. Users that need python2 compatibility may still download that old version. I would recommend to move forward and drop support for python2.

**Comment by ericzolf** [comment]
Closed with #691
