### ISSUE TITLE
[BUG] 'CacheIndexable' object has no attribute 'WARNING'

### ISSUE THREAD

**Issue by llowrey** [rdiff-backup/rdiff-backup#864]
## Bug summary

Backups won't complete successfully. Traceback is output. The cause seems to be:

```
AttributeError: 'CacheIndexable' object has no attribute 'WARNING'
```

Backups using 2.0.5 work fine. Problems only occurred when upgrading from that version to 2.2.3.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.3
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.2
system:
  fs_encoding: utf-8
  platform: Linux-6.0.9-300.fc37.x86_64-x86_64-with-glibc2.36
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup
    --new
    --no-ssh-compression
    --terminal-verbosity 0
    --tempdir /backups/.tmp/
    backup
    --include-globbing-filelist bar.filter
    --not-compressed-regexp (?i).*\.(gz|z|bz|bz2|tgz|zip|rpm|deb|jpg|jpeg|gif|png|jp2|mp3|ogg|avi|wmv|mpeg|mpg|rm|mov|flac|shn|pgp|gpg|rz|lzh|zoo|lharc|rar|[rs][0-9][0-9]|arj|asc|vob|iso|mkv|ts|m2ts|ac3|h264|dts|ty|tmf)$
    --preserve-numerical-ids
    --exclude-if-present NO_BACKUP
    --exclude-other-filesystems
    --exclude-sockets
    --no-compare-inode
    --no-eas
    bar-backup::/
    /backups/bar/
```

## What happened and what did you expect?

```
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.2.3', 'console_scripts', 'rdiff-backup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 105, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/actions/backup.py", line 154, in run
    backup.mirror_and_increment_compat200(
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/backup.py", line 53, in mirror_and_increment_compat200
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/backup.py", line 208, in patch_and_increment
    for diff in rorpiter.FillInIter(source_diffiter, dest_rpath):
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/rorpiter.py", line 406, in FillInIter
    for rp in rpiter:
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/iterfile.py", line 430, in __next__
    type, data = self._get()
                 ^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/iterfile.py", line 472, in _get
    self.buf += self.file.read()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/connection.py", line 647, in read
    return self.connection.VirtualFile.readfromid(self.id, length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/connection.py", line 579, in __call__
    return self.connection.reval(*(self.call_name, ) + args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/connection.py", line 434, in reval
    raise result
AttributeError: 'CacheIndexable' object has no attribute 'WARNING'
```

`backup.log` does not show anything more interesting, even with `--verbosity 9`. Processing seems to always stop somewhere in `/var/lib/selinux/targeted/active/modules/100/` but the actual directory/file is different each execution.

## More information

Server end is `chroot`ed inside a btrfs snapshot of the host root filesystem. The command-line is:
```
chroot $MNT rdiff-backup --terminal-verbosity 0 server
```

**Comment by ericzolf** [comment]
Few questions:

1. Do you use rdiff-backup in client/server mode? I ask because you list a server command but don't use it in your client command. 
2. Same version on both sides? 
3. I would need to see more from the output, especially on the server side in debug mode,  only the last output on the client side isn't enough. I need more context. 
4. You call with --new but use the old syntax...

**Comment by ericzolf** [comment]
Forget my last comment. Oversaw the "backup" action. Still "--new" isn't required.

**Comment by llowrey** [comment]
1. Yes, client-server.
2. Yes, same version. Both pulled from the Fedora 37 repo.
3. I found the problem by a bit of trial and error. The file `imjournal.state` was duplicated 3 times in `/var/lib/rsyslog`. Once I had that info I found the relevant log entries. After cleaning up those duplicated files the backup ran just fine.

```
2023-03-05 11:54:35.589020 -0500  <CLIENT-2806213>  * Processing file lib/rsyslog/imjournal.state
2023-03-05 11:54:35.589245 -0500  <CLIENT-2806213>  DEBUG: Regular copying input path lib/rsyslog/imjournal.state to output path /backups/bar-var/lib/rsyslog/rdiff-backup.tmp.19928
        Index=('lib', 'rsyslog', 'imjournal.state')
2023-03-05 11:54:35.589454 -0500  <CLIENT-2806213>  DEBUG: Renaming from path /backups/bar-var/lib/rsyslog/rdiff-backup.tmp.19928 to path /backups/bar-var/lib/rsyslog/imjournal.state
2023-03-05 11:54:35.589521 -0500  <CLIENT-2806213>  * Processing file lib/rsyslog/imjournal.state
2023-03-05 11:54:35.589546 -0500  <CLIENT-2806213>  WARNING: Repeated index (b'lib', b'rsyslog', b'imjournal.state'), bad filesystem?
2023-03-05 11:54:35.589599 -0500  <CLIENT-2806213>  * Processing file lib/rsyslog/imjournal.state
2023-03-05 11:54:35.589614 -0500  <CLIENT-2806213>  WARNING: Repeated index (b'lib', b'rsyslog', b'imjournal.state'), bad filesystem?
```

**Comment by ericzolf** [comment]
How can a file system have 3 times the same file? Is this a speciality of btrfs?

**Comment by llowrey** [comment]
Ha, yes, btrfs never ceases to entertain. It was the same dirent duplicated three times. Everything was the same (eg inode).

**Comment by ericzolf** [comment]
Weird but ok, closing the issue.
